spring.application.name=payments

# Activam consola web pentru a vedea baza de date
spring.h2.console.enabled=true

# Alegem un URL simplu pentru ea
spring.datasource.url=jdbc:h2:mem:bancadb

# Ne asiguram ca nu cere o parola complicata
spring.datasource.username=sa
spring.datasource.password=